### ISSUE TITLE
relational_tucker3.relation_embedder.base_embedder.dim = -1 causes error

### ISSUE THREAD

**Issue by tsafavi** [uma-pi1/kge#118]
When I try to run an RT3 training job without explicitly setting `relational_tucker3.relation_embedder.base_embedder.dim`, I get a PyTorch error about creating a Tensor with a negative dimension. This is because the default config file (kge/model/relational_tucker3.yaml) sets `relational_tucker3.relation_embedder.base_embedder.dim = -1`, which doesn't appear to be updated anywhere when the embeddings are initialized. Is the -1 supposed to be referring to `relational_tucker3.relation_embedder.dim` (which is automatically set to the entity embedding dim ** 2) perhaps?  

Config file to replicate error: 
```
job.type: train
dataset.name: toy
model: relational_tucker3

relational_tucker3:
  entity_embedder:
    dim: 50
    dropout: 0.02
    regularize: 'lp'
    regularize_args:
      weight: 4e-12

  relation_embedder:
    dropout: 0.3
    regularize: 'lp'
    regularize_args:
      weight: 6e-16

train:
  max_epochs: 50
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
```
