### ISSUE TITLE
Not able to achieve published training performance

### ISSUE THREAD

**Issue by lvermue** [uma-pi1/kge#161]
Hi LibKGE-Team,
Amazed by the results you show in Table 2 from the [paper](https://www.aclweb.org/anthology/2020.emnlp-demos.22.pdf) for this library, I've been trying to understand how you get it that fast.

To start, I have installed the latest version of this repository.
For the test I created following script, this particular example for 1024 negative samples:
```
job.type: train
dataset.name: fb15k
model: complex

train:
  type: negative_sampling
  optimizer: Adagrad
  optimizer_args:
    lr: 0.6
  loss: bce
  loss_arg: 0.0
  batch_size: 512
  num_workers: 4

lookup_embedder.dim: 128

negative_sampling:
  num_samples:
    s: 512
    o: 512 
```

I invoke the training by running
`kge start examples/my-example-above.yaml`

I run this on a Titan XP GPU with CUDA 10.2, and an Intel Xeon E5-2620 v4.0 CPU, dataset on SSD.
It's not the exact hardware, but similar, yet it takes about ~65 seconds per epoch for me instead of the ~14 seconds I was expecting.
Also when I try to run 16384 negative samples, I get CUDA OOM errors.
Did I miss something in the configuration?
