### ISSUE TITLE
Model not being loaded correctly

### ISSUE THREAD

**Issue by oliver-lloyd** [uma-pi1/kge#196]
Hello, 

I am trying to start a grid search from a .yaml configuration file, but am repeatedly met with this same traceback:

```
Traceback (most recent call last):
  File "/home/fu19841/miniconda3/envs/libkge/bin/kge", line 33, in <module>
    sys.exit(load_entry_point('libkge', 'console_scripts', 'kge')())
  File "/home/fu19841/LPComparison/scripts/kge/kge/cli.py", line 285, in main
    job.run()
  File "/home/fu19841/LPComparison/scripts/kge/kge/job/job.py", line 153, in run
    self._prepare()
  File "/home/fu19841/LPComparison/scripts/kge/kge/job/eval_entity_ranking.py", line 52, in _prepare
    super()._prepare()
  File "/home/fu19841/LPComparison/scripts/kge/kge/job/eval.py", line 56, in _prepare
    self.model.prepare_job(self)  # let the model add some hooks
AttributeError: 'NoneType' object has no attribute 'prepare_job'
```

I have been able to run the provided example jobs with this installation of LibKGE, so I suspect the problem lies within the configuration YAML, but as far as I can tell the desired model is specified correctly. Any help diagnosing the configuration issue would be greatly appreciated.

(For context, this YAML was automatically derived from the configuration of the best performing trial within a previous ax gridsearch run in LibKGE. The purpose of this current job is to assess the effect on performance of changing one parameter while holding all the rest steady at their 'best' values.)

```
1vsAll:
  class_name: TrainingJob1vsAll
KvsAll:
  class_name: TrainingJobKvsAll
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
ax_search:
  class_name: AxSearchJob
  num_sobol_trials: 100
  num_trials: 100
  parameter_constraints: []
  parameters:
  - name: model
    type: fixed
    value: transe
  - name: train.lr_scheduler
    type: fixed
    value: ReduceLROnPlateau
  - name: train.lr_scheduler_args.mode
    type: fixed
    value: max
  - name: train.lr_scheduler_args.factor
    type: fixed
    value: 0.95
  - name: train.lr_scheduler_args.threshold
    type: fixed
    value: 0.0001
  - name: lookup_embedder.initialize_args.normal_.mean
    type: fixed
    value: 0.0
  - name: lookup_embedder.initialize_args.xavier_uniform_.gain
    type: fixed
    value: 1.0
  - name: lookup_embedder.initialize_args.xavier_normal_.gain
    type: fixed
    value: 1.0
  - name: train.type
    type: fixed
    value: 1vsAll
  - name: train.loss
    type: fixed
    value: kl
  - name: train.optimizer
    type: fixed
    value: Adam
  - name: train.optimizer_args.lr
    type: fixed
    value: 0.02637398760958916
  - name: train.lr_scheduler_args.patience
    type: fixed
    value: 5
  - name: lookup_embedder.dim
    type: fixed
    value: 128
  - name: lookup_embedder.initialize
    type: fixed
    value: xavier_normal_
  - name: lookup_embedder.initialize_args.uniform_.a
    type: fixed
    value: -0.2093200850727409
  - name: lookup_embedder.regularize
    type: fixed
    value: lp
  - name: lookup_embedder.regularize_args.weighted
    type: fixed
    value: true
  - name: transe.entity_embedder.regularize_weight
    type: fixed
    value: 0.0005230893478826013
  - name: transe.relation_embedder.regularize_weight
    type: fixed
    value: 1.3262482044045084e-19
  - name: transe.entity_embedder.dropout
    type: fixed
    value: -0.32426406163722277
  - name: transe.relation_embedder.dropout
    type: fixed
    value: 0.23354650381952524
  - bounds:
    - 1.0e-05
    - 1.0
    log_scale: true
    name: lookup_embedder.initialize_args.normal_.std
    type: range
  sobol_seed: 0
console:
  format: {}
  quiet: false
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_ids.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      size: 661
      split_type: test
      type: triples
    test_without_unseen:
      filename: test_without_unseen.del
      size: 661
      split_type: test
      type: triples
    train:
      filename: train.del
      size: 5216
      split_type: train
      type: triples
    train_sample:
      filename: train_sample.del
      size: 652
      split_type: train
      type: triples
    valid:
      filename: valid.del
      size: 652
      split_type: valid
      type: triples
    valid_without_unseen:
      filename: valid_without_unseen.del
      size: 652
      split_type: valid
      type: triples
  name: umls
  num_entities: 135
  num_relations: 46
  pickle: true
entity_ranking:
  chunk_size: -1
  class_name: EntityRankingJob
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: false
    relation_type: true
  tie_handling: rounded_mean_rank
eval:
  batch_size: 256
  num_workers: 0
  pin_memory: false
  split: valid
  trace_level: epoch
  type: entity_ranking
grid_search:
  class_name: GridSearchJob
  parameters:
    +++: +++
  run: true
import:
- transe
job:
  device: cuda
  type: eval
lookup_embedder:
  class_name: LookupEmbedder
  dim: 128
  dropout: 0.0
  initialize: xavier_normal_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 9.008426045013616e-05
    uniform_:
      a: -0.2093200850727409
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 3
    weighted: true
  regularize_weight: 0.0
  round_dim_to: []
  sparse: false
manual_search:
  class_name: ManualSearchJob
  configurations: []
  run: true
model: transe
modules:
- kge.model.embedder
- kge.model
- kge.job
negative_sampling:
  class_name: TrainingJobNegativeSampling
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: batch
  num_samples:
    o: -1
    p: 0
    s: 3
  sampling_type: uniform
  shared: false
  shared_type: default
  with_replacement: true
random_seed:
  default: -1
  numba: -1
  numpy: -1
  python: -1
  torch: -1
search:
  device_pool: []
  num_workers: 1
  on_error: abort
  type: ax_search
train:
  abort_on_nan: true
  auto_correct: true
  batch_size: 4096
  checkpoint:
    every: 5
    keep: 3
    keep_init: true
  loss: kl
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  lr_warmup: 0
  max_epochs: 400
  num_workers: 0
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.02637398760958916
      type: Adam
  pin_memory: false
  split: train
  subbatch_auto_tune: false
  subbatch_size: -1
  trace_level: epoch
  type: 1vsAll
  visualize_graph: false
training_loss:
  class_name: TrainingLossEvaluationJob
transe:
  class_name: TransE
  entity_embedder:
    +++: +++
    dropout: -0.32426406163722277
    regularize_weight: 0.0005230893478826013
    type: lookup_embedder
  l_norm: 1.0
  relation_embedder:
    +++: +++
    dropout: 0.23354650381952524
    regularize_weight: 1.3262482044045084e-19
    type: lookup_embedder
user:
  +++: +++
valid:
  early_stopping:
    patience: 10
    threshold:
      epochs: 50
      metric_value: 0.05
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: float("nan")
  metric_max: true
  split: valid
  trace_level: epoch

```
