### ISSUE TITLE
Errors occurred when trying to add a new embedder class

### ISSUE THREAD

**Issue by jwzhi** [uma-pi1/kge#232]
Hi, 

I want to build the GCN embedders on top of kge. But I have encountered the `KeyError: 'gcn_embedder'` which I am not sure how to solve. I add the embedder class according to the README but it seems that there must be a place I forgot to add or change, any insight will be helpful!

In `kge/model/embedder`, I created it a new `gcn_embedder.py` and a `gcn_embedder.yaml`. The `gcn_embedder.py` looks like this 
```import torch.nn
import torch.nn.functional
from kge.model import KgeEmbedder

from dgl.nn.pytorch import GraphConv
import pdb

class GCNEmbedder(KgeEmbedder):
    """Adds a linear projection layer to a base embedder."""
    """ gcn embedder """

    def __init__(
        self, config, dataset, configuration_key, vocab_size, init_for_load_only=False
    ):
        super().__init__(
            config, dataset, configuration_key, init_for_load_only=init_for_load_only
        )

        # initialize base_embedder
        if self.configuration_key + ".base_embedder.type" not in config.options:
            config.set(
                self.configuration_key + ".base_embedder.type",
                self.get_option("base_embedder.type"),
            )
        self.base_embedder = KgeEmbedder.create(
            config, dataset, self.configuration_key + ".base_embedder", vocab_size
        )

        self.g = dataset.construct_graph().to('cuda:0')
        # self.g = dataset.construct_graph()
        self.emb_dim = self.get_option("entity_embedder.dim")
        dropout = self.get_option("encoder.dropout")
        if dropout < 0.0:
            if config.get("train.auto_correct"):
                config.log(
                    "Setting {}.encoder.dropout to 0., "
                    "was set to {}.".format(configuration_key, dropout)
                )
                dropout = 0.0
        self.encoder = torch.nn.ModuleList()
        self.num_layers = self.get_option("encoder.num_layers")
        self.in_dim = self.get_option("encoder.in_dim")
        self.dim = self.get_option("encoder.dim")
        self.encoder.append(GraphConv(self.in_dim, self.dim))
        for i in range(self.num_layers-1):
            self.encoder.append(GraphConv(self.dim, self.dim))
        #Dropout after compGCN layers
        self.dropouts = torch.nn.ModuleList()
        for i in range(self.num_layers):
            self.dropouts.append(
                torch.nn.Dropout(dropout)
            )     

    def _embed(self, embeddings, indexes):
        n_feats = embeddings
        for layer, dropout in zip(self.encoder, self.dropouts):
            n_feats = layer(self.g, n_feats)
            n_feats = dropout(n_feats)
        embeddings = n_feats[indexes]
        return embeddings

    def embed(self, indexes):
        return self._embed(self.base_embedder.embed_all(), indexes)

    def embed_all(self):
        return self._embed(self.base_embedder.embed_all(), indexes)

    def penalty(self, **kwargs):
        # TODO factor out to a utility method
        if self.regularize == "" or self.get_option("regularize_weight") == 0.0:
            result = []
        elif self.regularize == "lp":
            p = self.get_option("regularize_args.p")
            result = [
                (
                    f"{self.configuration_key}.L{p}_penalty",
                    self.get_option("regularize_weight")
                    * self.projection.weight.norm(p=p).sum(),
                )
            ]
        else:
            raise ValueError("unknown penalty")

        return super().penalty(**kwargs) + result + self.base_embedder.penalty(**kwargs)
```
And the `gcn_embedder.yaml` looks like this
```
import: [lookup_embedder]

encoder:
  class_name: GCNEmbedder
  base_embedder:
    type: lookup_embedder
    +++: +++                  # -1 means: same as base_embedder
  initialize: normal_          # xavier, uniform, normal
  initialize_args:
    +++: +++
  dropout: 0.                 # dropout used for embeddings
  regularize: 'lp'              # '', 'lp'
  regularize_weight: 0.0
  regularize_args:
    p: 2.0
  # see dgl.graphconv
  in_dim: 256                    # the input dimension
  dim: 256        # the dimension of the gcn layers
  dropout: 0.3
  activation: relu             # relu or gelu

  num_layers: 3                # the number of sub-encoder-layers in the encoder
```
in `kge/model/__init__.py`, I added `from kge.model.embedder.gcn_embedder import GCNEmbedder` into it. 

Is there anything more that I need to change? Thanks again for your help. I appreciate it.
