### ISSUE TITLE
How to stack user-defined embedder to the current decoder models

### ISSUE THREAD

**Issue by jwzhi** [uma-pi1/kge#233]
Hi, thanks again for solving the issue of adding embedder classes.  I am trying to extend libkge by adding new embedders and use them on the existing decoder-only models (TransE, DistMult etc.) One issue that I am encountering is, I do not know how to stack my newly defined embedder on the decoder models. For example, if I want to use gcn (embedder) + distmult (decoder), what is the correct way to write the config? 
In `distmult.yaml`, I changed it to 
```import: [lookup_embedder]

distmult:
  class_name: DistMult
  entity_embedder:
    type: gcn_embedder
    +++: +++
  relation_embedder:
    type: lookup_embedder
    +++: +++ 
```

But it will raise the following error 
```[b26706d1] Failed to create embedder gcn_embedder (class GCNEmbedder).
[b26706d1] Failed to create model distmult (class DistMult).
[b26706d1] Failed to create model reciprocal_relations_model (class ReciprocalRelationsModel).
Traceback (most recent call last):
  File "/datadrive/data/KG-GNN/kge/kge/config.py", line 56, in get
    result = result[name]
KeyError: 'type'
```
My embedder is appended as follows, in gcn_embedder.yaml
```
import: [lookup_embedder]

gcn_embedder:
  class_name: GCNEmbedder
  base_embedder:
    type: lookup_embedder
    +++: +++                  # -1 means: same as base_embedder
  initialize: normal_          # xavier, uniform, normal
  initialize_args:
    +++: +++
  dropout: 0.                 # dropout used for embeddings
  regularize: 'lp'              # '', 'lp'
  regularize_weight: 0.0
  regularize_args:
    p: 2.0
  # see dgl.graphconv
  in_dim: 256                    # the input dimension
  dim: 256        # the dimension of the gcn layers
  dropout: 0.3
  activation: relu             # relu or gelu

  num_layers: 3                # the number of sub-encoder-layers in the encoder
```

In `gcn_embedder.py`, 
```import torch.nn
import torch.nn.functional
from kge.model import KgeEmbedder

from dgl.nn.pytorch import GraphConv
import pdb

class GCNEmbedder(KgeEmbedder):
    """Adds a linear projection layer to a base embedder."""
    """ gcn embedder """

    def __init__(
        self, config, dataset, configuration_key, vocab_size, init_for_load_only=False
    ):
        super().__init__(
            config, dataset, configuration_key, init_for_load_only=init_for_load_only
        )

        # initialize base_embedder
        if self.configuration_key + ".base_embedder.type" not in config.options:
            config.set(
                self.configuration_key + ".base_embedder.type",
                self.get_option("base_embedder.type"),
            )
        self.base_embedder = KgeEmbedder.create(
            config, dataset, self.configuration_key + ".base_embedder", vocab_size
        )

        self.g = dataset.construct_graph().to('cuda:0')
        # self.g = dataset.construct_graph()
        self.emb_dim = self.get_option("entity_embedder.dim")
        dropout = self.get_option("encoder.dropout")
        if dropout < 0.0:
            if config.get("train.auto_correct"):
                config.log(
                    "Setting {}.encoder.dropout to 0., "
                    "was set to {}.".format(configuration_key, dropout)
                )
                dropout = 0.0
        self.encoder = torch.nn.ModuleList()
        self.num_layers = self.get_option("encoder.num_layers")
        self.in_dim = self.get_option("encoder.in_dim")
        self.dim = self.get_option("encoder.dim")
        self.encoder.append(GraphConv(self.in_dim, self.dim))
        for i in range(self.num_layers-1):
            self.encoder.append(GraphConv(self.dim, self.dim))
        #Dropout after compGCN layers
        self.dropouts = torch.nn.ModuleList()
        for i in range(self.num_layers):
            self.dropouts.append(
                torch.nn.Dropout(dropout)
            )   
        print("initialized GCN Embedder")  

    def _embed(self, embeddings, indexes):
        n_feats = embeddings
        for layer, dropout in zip(self.encoder, self.dropouts):
            n_feats = layer(self.g, n_feats)
            n_feats = dropout(n_feats)
        embeddings = n_feats[indexes]
        return embeddings

    def embed(self, indexes):
        return self._embed(self.base_embedder.embed_all(), indexes)

    def embed_all(self):
        return self._embed(self.base_embedder.embed_all(), indexes)

    def penalty(self, **kwargs):
        # TODO factor out to a utility method
        if self.regularize == "" or self.get_option("regularize_weight") == 0.0:
            result = []
        elif self.regularize == "lp":
            p = self.get_option("regularize_args.p")
            result = [
                (
                    f"{self.configuration_key}.L{p}_penalty",
                    self.get_option("regularize_weight")
                    * self.projection.weight.norm(p=p).sum(),
                )
            ]
        else:
            raise ValueError("unknown penalty")

        return super().penalty(**kwargs) + result + self.base_embedder.penalty(**kwargs)
```

Thanks in advance
