### ISSUE TITLE
Conve's embedder dimension discrepancy

### ISSUE THREAD

**Issue by jwzhi** [uma-pi1/kge#239]
Hi,

I wonder why there is a dimension discrepancy between the dimension my config file sets and the actual model's dimension only for the ConvE implementation. 
For example, if I set 
```
reciprocal_relations_model:
  base_model:
    type: conve
    entity_embedder:
      dim: 200
      dropout: 0.3
```
in my `config.yaml`. 
The actual embedder in the kge model is 
```
(_entity_embedder): LookupEmbedder(
      (_embeddings): Embedding(14541, 201)
      (dropout): Dropout(p=0.3, inplace=False)
    )
```
This is really weird. And I tried with some other score functions such as distmult, transe and they seem to be fine. Do you have an idea why this happens for conve? 

Thanks,
