### ISSUE TITLE
Uniform initialization interval

### ISSUE THREAD

**Issue by nomisto** [uma-pi1/kge#244]
Hello,

First of all thanks for your work, very helpful framework!

I've got a quick question about hyperparameter search and the uniform initialization interval. In the configs used for the paper you set 

```yaml
    - name: lookup_embedder.initialize_args.uniform_.a
      type: range
      bounds: [-1.0, -0.00001]
```

and in the table regarding the hyperparameter search space in the paper you say:
> Interval (Unif) [−1.0,1.0]

so I would assume that `b = -1 * a`, however in the codebase it says the opposite (`a = -1 * b`), ist this a bug or did I overlook something?

https://github.com/uma-pi1/kge/blob/d0634774b1b29afc739454737aa105dec6cb60b2/kge/model/kge_model.py#L76-L80
