### ISSUE TITLE
How to run kge test on train split

### ISSUE THREAD

**Issue by jwzhi** [uma-pi1/kge#248]
Hi,

I want to run the kge test command on the train split instead of the test split as a sanity check for my user-defined model (if the model is really learning anything meaningful) But I cannot really find a way to do this. Can you point me to how to specify the config arguments? 

The one I tried is 
```
dataset:
  name: fb15k-237
  files:
    test:
      filename: train.del
      type: triples
```
And it does not work.
